### ISSUE TITLE
Helm chart doesnt install correctly for CoreOS

### ISSUE THREAD

**Issue by hr1sh1kesh** [portworx/helm#19]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:

**What you expected to happen**:
CoreOS installation of the chart fails. The volume mounts are incorrect when using a docker container.  Needs validation on Tectonic. 

**How to reproduce it (as minimally and precisely as possible)**:
Install the helm chart on tectonic. 

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hrishipx** [comment]
Issue has been fixed with the latest helm chart changes.
