### ISSUE TITLE
Cleanup previously failed jobs upon helm install

### ISSUE THREAD

**Issue by hr1sh1kesh** [portworx/helm#24]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
If the preinstall hook fails it stays in the Error state. Subsequent installs are blocked stating the preinstall hook is already present. The user needs to manually delete the previously failed hook. 

**What you expected to happen**:
The install process for a user should be idempotent in nature. This would help the install process.

**How to reproduce it (as minimally and precisely as possible)**:
helm install. Make sure there is an erroneous etcd url passed. This would cause the pre-install hook to fail. 
helm install again with the right etcd url. The install will error stating `preinstall hook already exists`

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hr1sh1kesh** [comment]
Write a pre-install hook which runs as the first hook which deletes the previously left over jobs. 
In the meantime make sure that the `pre-install hook` has a unique name per release.

**Comment by harsh-px** [comment]
fixed by https://github.com/portworx/helm/pull/26
