### ISSUE TITLE
helm chart did not recognize/ handle etcdEndpoint passed into "helm install"

### ISSUE THREAD

**Issue by sathyan316** [portworx/helm#31]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Executed the command below:
helm install --name=px --namespace kube-system --set deploymentType=oci,imageVersion=1.2.16,etcdEndpoint=etcd:https://kube-etcd.kube-system:2379,clusterName=myCluster px-1.0.0.tgz
Failed with:
Error: render error in "px/templates/portworx-ds.yaml": template: px/templates/portworx-ds.yaml:93:18: executing "px/templates/portworx-ds.yaml" at <required "A valid ET...>: error calling required: A valid ETCD url in the format etcd:http://<your-etcd-endpoint> is required. Verify that the key is correct and there isnt any typo in specifying that, also ensure it is accessible from all node of your kubernetes cluster

**What you expected to happen**:
helm install should work

**How to reproduce it (as minimally and precisely as possible)**:
Run the command mentioned above

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version:
docker 1.12, helm 2.7, kubernetes RKE-1.8.7
- Cloud provider or hardware configuration:
VMware ESXi 6.0 Update 2
- OS (e.g. from /etc/os-release):
CoreOS
- Kernel (e.g. `uname -a`):
4.13.9
- Install tools:
- Others:

**Comment by hr1sh1kesh** [comment]
@sathyan316 there looks like a typo in the endpoint parameter passed to the chart. 
needs to be `etcdEndPoint` rather than `etcdEndpoint`

**Comment by hr1sh1kesh** [comment]
Error with passing the parameter incorrectly. Closing.
