### ISSUE TITLE
Can't install GKE 1.10.6 /opt/pwx Read-only

### ISSUE THREAD

**Issue by Rajczyk** [portworx/helm#54]
**Is this a BUG REPORT or FEATURE REQUEST?**:  BUG REPORT

**What happened**: oci-monitor container fails to start 

**What you expected to happen**: oci-monitor container to start

**How to reproduce it (as minimally and precisely as possible)**:
GKE 
ContainerOS
Kubernetes 1.10.6
ETCD

Any help to get this installed would be appreciated.

**Comment by harsh-px** [comment]
@Rajczyk Portworx doesn't support ContainerOS. Please use Ubuntu as the image when creating the cluster. More information is here: https://docs.portworx.com/cloud/gcp/gke.html
