### ISSUE TITLE
Syntax error in preinstall hook

### ISSUE THREAD

**Issue by seroyer** [portworx/helm#79]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
Syntax error in preinstall hook
```# kubectl logs px-hook-etcd-preinstall-qvb94 -n kube-system
Initializing...
/usr/bin/etcdStatus.sh: line 34: syntax error near unexpected token `else'
/usr/bin/etcdStatus.sh: line 34: `    else'
```

**What you expected to happen**:
Should there be a `then` after the if?

**How to reproduce it (as minimally and precisely as possible)**:
Supply etcd cacert but not cert/key

**Anything else we need to know?**:
Seems to have been introduced by https://github.com/portworx/helm/pull/78

**Environment**:
- Container Orchestrator and version: k8s 1.10
- Cloud provider or hardware configuration: IKS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by seroyer** [comment]
Thanks for fixing this.  Will the docker image with the fix be published at some point?

https://hub.docker.com/r/portworx/px-etcd-preinstall-hook/tags

**Comment by harsh-px** [comment]
I'm in the process of updating that now.

**Comment by harsh-px** [comment]
@seroyer v1.2 of the preinstall-hook will have the fix. I've updated the templates in the chart to reference that image. Please fetch the latest master branch and give it a whirl.

**Comment by seroyer** [comment]
I verified the syntax error is fixed.  Thanks.
